# Minimal Trivy configuration used by CI scans
# See: https://aquasecurity.github.io/trivy/latest/docs/configuration/config-file/
format: sarif
exit-code: 1
severity: CRITICAL
# scanners can include vuln, secret, misconfig, license
scanners:
  - vuln
